In [2]:
import numpy as np


In [3]:
virat_runs= np.array([66,98,67])

In [4]:
player_ages=np.array((35,37,31))
print(player_ages)

[35 37 31]


In [5]:
strike_rates=np.array([120,135.5,98])
print(strike_rates)

[120.  135.5  98. ]


In [8]:
overs=np.array([4,10,7],dtype=float)
print(overs)

[ 4. 10.  7.]


In [10]:
zeros=np.zeros((2,3))
print(zeros)

[[0. 0. 0.]
 [0. 0. 0.]]


In [11]:
ones=np.ones((3,2))
ones

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [13]:
np.full((2,3),8)

array([[8, 8, 8],
       [8, 8, 8]])

In [16]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [26]:
empty=np.empty((2,2))
print(empty)

[[1. 1.]
 [1. 1.]]


In [29]:
arr=np.arange(55,65)
print(arr)
print(arr[0],arr[-1],arr[6])

[55 56 57 58 59 60 61 62 63 64]
55 64 61


In [31]:
print(np.arange(0,1,0.25))

[0.   0.25 0.5  0.75]


In [ ]:
batting_avg=np.linspace(30,50,5)
print(batting_avg)

[30. 35. 40. 45. 50.]


In [41]:
np.random.seed(42)


strike_rates= np.random.uniform(100,200,10)
print(strike_rates)

[137.45401188 195.07143064 173.19939418 159.86584842 115.60186404
 115.59945203 105.80836122 186.61761458 160.11150117 170.80725778]


In [40]:


strike_rates= np.random.uniform(100,200,10)
print(strike_rates)

[160.99966578 183.31949117 117.33646535 139.10606076 118.22360878
 175.53614103 142.51558745 120.79416629 156.77003278 103.13132925]


In [38]:
runs= np.random.randint(1,151,(2,3))
print(runs)

[[ 51 108  55]
 [ 64 131  51]]


In [ ]:
#2*3 matrix of batting averages from a normal distribution

batting_avg= np.random.normal(40,5,(2,3))
print(batting_avg)


[[37.65262807 42.71280022 37.68291154]
 [37.67135123 41.20981136 30.43359878]]


In [43]:
economy_zscores= np.random.randn(2,3)
print(economy_zscores)



[[-1.72491783 -0.56228753 -1.01283112]
 [ 0.31424733 -0.90802408 -1.4123037 ]]


In [44]:
win_prob = np.random.rand(5)
print(win_prob)

[0.45606998 0.78517596 0.19967378 0.51423444 0.59241457]


In [45]:
squad= np.array(["Virat", "Rohit", "Rahul", "Gill", "Pant"])
print(np.random.choice(squad,3,replace=False))

['Rohit' 'Gill' 'Pant']


In [74]:
rng=np.random.default_rng(42)
print(rng.integers(1,7,10))

[1 5 4 3 3 6 1 5 2 1]


In [75]:
sales= [0,5,155,0,518,616]
sales_array= np.array(sales)

In [76]:
print(sales_array.shape)
print(sales_array.size)
print(sales_array.dtype)

(6,)
6
int32


In [79]:
store_sales = np.array([
    [120,135,150,160],
    [90,110,105,130],
    [200,180,210,220]
])
print(store_sales.ndim)

2


In [80]:

print(store_sales.shape)
print(store_sales.size)

(3, 4)
12


In [82]:
result_array= np.where(sales_array==0, "No sales", "Some sales")
print(result_array)

['No sales' 'Some sales' 'Some sales' 'No sales' 'Some sales' 'Some sales']


In [83]:
bool_mask= sales_array != 0
print(bool_mask)

[False  True  True False  True  True]


In [84]:
filtered_sales = sales_array[bool_mask]
print(filtered_sales)

[  5 155 518 616]


In [85]:
marks= np.array([55,68,72,49,83,91,37,65,78,59,88])
print(marks[8])
print(marks[-1])
print(marks[1:5])
print(marks[:3])
print(marks[-3:])
print(marks[::2])
print(marks[::-1])


78
88
[68 72 49 83]
[55 68 72]
[78 59 88]
[55 72 83 37 78 88]
[88 59 78 65 37 91 83 49 72 68 55]


In [86]:
marks[0:3] =75
print(marks)

[75 75 75 49 83 91 37 65 78 59 88]


In [87]:
marks= np.array([55,68,72,49,83,91,37,65,78,59,88])
top_batch = marks[0:5]
print(top_batch)
print(marks)

[55 68 72 49 83]
[55 68 72 49 83 91 37 65 78 59 88]


In [ ]:
marks= np.array([55,68,72,49,83,91,37,65,78,59,88])
marks_copy = marks.copy()  #deep copy
marks_copy[3]=99
print(marks_copy)
print(marks)  # original unchanged

[55 68 72 99 83 91 37 65 78 59 88]
[55 68 72 49 83 91 37 65 78 59 88]


In [91]:
marks = np.array([69,26,78,91,54,34])
passed = marks >= 35
print(passed)
print(marks[passed])
print(marks[marks>70])

[ True False  True  True  True False]
[69 78 91 54]
[78 91]


In [92]:
print(marks[(marks>=50) & (marks<80)])
print(marks[(marks<355) | (marks>90)])
print(marks[~passed])
print(np.sum(marks<35))

[69 78 54]
[69 26 78 91 54 34]
[26 34]
2


In [ ]:
print("Total: ", sales.sum())
print("mean: ", sales.mean())
print("median: ", np.median(sales))
print("min: ", sales min(), "max: ",sales.max())
print("range: ", np.ptp(sales))
print("var:  ", sales.var().round(2))
print("std:  ", sales.std().round(2))
q1, q2, q3= np.percentile(sales, [25,50,75])
print("Q1, Q2, Q3:",q1,q2,q3," IQR:", q3-q1)
print("")

In [94]:
store_sales=np.random.randint(100,500,12).reshape(3,4)

In [95]:
print(store_sales.sum())
print(store_sales.sum(axis=1))

3692
[1187 1203 1302]


In [99]:
marks=np.array([78,95,88,67,91])
names=np.array(['amit','neha','raj','adithi','kiran'])
print(np.sort(marks))
print(np.sort(marks)[::-1])
order=np.argsort(-marks)
print(order)
print(names[order])
print(marks[order])

[67 78 88 91 95]
[95 91 88 78 67]
[1 4 2 0 3]
['neha' 'kiran' 'raj' 'amit' 'adithi']
[95 91 88 78 67]


In [102]:
expenses=np.array([2500,3200,np.nan,4100,3900,np.nan,3000])
print(expenses)
print(expenses.sum())
print(expenses.mean())
print(np.nan==np.nan)
missing=np.isnan(expenses)
print(missing)
missing.sum()

[2500. 3200.   nan 4100. 3900.   nan 3000.]
nan
nan
False
[False False  True False False  True False]


2

In [103]:
missing=np.isnan(expenses)
print(missing)
print("Missing count: ",missing.sum())

[False False  True False False  True False]
Missing count:  2


In [104]:
clean= expenses[~np.isnan(expenses)]
print(clean)

[2500. 3200. 4100. 3900. 3000.]


In [105]:
print(np.nan_to_num(expenses,nan=0))

[2500. 3200.    0. 4100. 3900.    0. 3000.]


In [106]:
filled = np.where(np.isnan(expenses), np.nanmean(expenses),expenses)
print(filled.round(2))

[2500. 3200. 3340. 4100. 3900. 3340. 3000.]
